name: Build macOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: chmod +x build-xcode.sh
      - name: Build
        run: ./build-xcode.sh
